spring:
  application:
    name: server-archive
  datasource:
    url: jdbc:postgresql://119.205.220.48:5432/NEW_CSERVER
    username: yubi
    password: dbql2024!@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false  # 개발 중일 때는 false
    encoding: UTF-8  # 템플릿 파일의 인코딩 설정

springdoc:
  api-docs:
    path: /api-docs   # API 문서 경로 설정
  swagger-ui:
    path: /swagger-ui   # Swagger UI 접근 경로 설정

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
